export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const ENABLE_EDITOR_MODE = 'ENABLE_EDITOR_MODE';
export const DISABLE_EDITOR_MODE = 'DISABLE_EDITOR_MODE';
export const CHANGE_EDITOR_ELEM = 'CHANGE_EDITOR_ELEM';